# Veri Dönüştürme

In [1]:
import pandas as pd

In [2]:
veri=pd.DataFrame({"a":["one","two"]*3,"b":[1,1,2,3,2,3]})
veri

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

duplicated() methodu verisetinde tekrar olup olmadığını söyler. Boolean değer döndürür.

In [3]:
veri.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

drop_duplicates() methodu tekrar eden değerleri kaldırır ve bir DataFrame yapısı döndürür.

In [4]:
veri.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

Belirli sütunlarda tekrar eden verileri bulabilmek için de kullanılır. Verisetimize önce bir sütun ekleyelim.

In [5]:
veri["c"]=range(6)

In [6]:
veri

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [7]:
veri.duplicated(["a"])

0    False
1    False
2     True
3     True
4     True
5     True
dtype: bool

In [8]:
veri.duplicated(["c"])

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [9]:
veri.duplicated(["a","c"])

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

Sondan başlayarak tekrar eden değerleri bulabilmek için keep="last" methodu kullanılır.

In [10]:
veri.duplicated(["a","c"],keep="last")

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

Bir fonksiyon ya da bir haritalama ile bir verinin değerlerini verisetine aktarabiliriz.

In [11]:
import pandas as pd


In [16]:
vs = pd.DataFrame({"isim": ["Ali", "can", "Nur", "efe", "Ata"], "puan": [60, 70, 80, 40, 90]})
vs

isim  puan
0  Ali    60
1  can    70
2  Nur    80
3  efe    40
4  Ata    90

In [17]:
sinif={"Ali":"A","Can":"B","Nur":"C","Efe":"D","Ata":"E"}

map() methodu kullanarak ekleme yapabiliriz.map() methodu Ya bir fonksiyon ya da sözlük yapısı kabul eder. İsimlerin bazılarının küçük bazılarının büyük olmasından dolayı önce isimlerin baş harflerini büyütmek için Capitalize() methodunu kullanıyoruz.

In [22]:
ad=vs["isim"].str.capitalize()

In [23]:
vs["sube"]=ad.map(sinif)

In [24]:
vs

isim  puan sube
0  Ali    60    A
1  can    70    B
2  Nur    80    C
3  efe    40    D
4  Ata    90    E

In [25]:
nt=pd.Series([80,70,90,54,60,45])

In [26]:
nt

0    80
1    70
2    90
3    54
4    60
5    45
dtype: int64

Örneğin 70 verisini eksik veri yapmak istersek; replace() methodunu kullanırız.

In [27]:
import numpy as np

In [28]:
nt.replace(70,np.nan)

0    80.0
1     NaN
2    90.0
3    54.0
4    60.0
5    45.0
dtype: float64

In [29]:
nt.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3    54.0
4     0.0
5    45.0
dtype: float64

In [30]:
nt.replace({80:100,54:4})

0    100
1     70
2     90
3      4
4     60
5     45
dtype: int64

Verisetindeki eksenler bir fonksiyon kullanılarak ya da bir haritalama işlemi yapılarak tekrar isimlendirilebilir.

In [31]:
df=pd.DataFrame(np.arange(12).reshape(3,4),index=[0,1,2],columns=["Ali","Efe","Eda","Can"])
df

Ali  Efe  Eda  Can
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [32]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)

In [33]:
df

Ali  Efe  Eda  Can
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

Rename() methodu ile satır ve sütun isimlerini büyük harf yapabiliriz. Bunun için str modülündeki methodları kullanabiliriz.

In [34]:
df.rename(index=str.title,columns=str.upper)

ALI  EFE  EDA  CAN
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [36]:
df.rename(index={"one":"X"},columns={"Can":"Ata"})

Ali  Efe  Eda  Ata
X        0    1    2    3
two      4    5    6    7
three    8    9   10   11

Bu komutlar ile verisetini kalıcı olarak değiştiremeyiz. Fakat inplace="True" opsiyonu ile kalıcı olarak değiştirmek mümkündür.

In [37]:
df.rename(index={"one":"X"},columns={"Can":"Ata"},inplace=True)

In [38]:
df

Ali  Efe  Eda  Ata
X        0    1    2    3
two      4    5    6    7
three    8    9   10   11

Veriyi belli aralıkta gruplandırmak istersek cut() methodu kullanılır.

In [39]:
nt=[30,80,40,50,60,90,70,55,65,97,100,65]

In [40]:
aralik=[20,40,60,80,100]

In [41]:
puan=pd.cut(nt,aralik)

In [42]:
puan

[(20, 40], (60, 80], (20, 40], (40, 60], (40, 60], ..., (40, 60], (60, 80], (80, 100], (80, 100], (60, 80]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

Her birinin kategorik kodunu görmek istersek codes opsiyonu kullanırız.

In [43]:
puan.codes

array([0, 2, 0, 1, 1, 3, 2, 1, 2, 3, 3, 2], dtype=int8)

In [44]:
puan.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [45]:
pd.value_counts(puan)

(60, 80]     4
(40, 60]     3
(80, 100]    3
(20, 40]     2
dtype: int64

In [46]:
puan=pd.cut(nt,aralik,right=False)

In [47]:
puan

[[20, 40), [80, 100), [40, 60), [40, 60), [60, 80), ..., [40.0, 60.0), [60.0, 80.0), [80.0, 100.0), NaN, [60.0, 80.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [48]:
isim=["düşük","orta","yüksek","tavan"]
pd.cut(nt,aralik,labels=isim)

['düşük', 'yüksek', 'düşük', 'orta', 'orta', ..., 'orta', 'yüksek', 'tavan', 'tavan', 'yüksek']
Length: 12
Categories (4, object): ['düşük' < 'orta' < 'yüksek' < 'tavan']

İstediğimiz aralık sayısını girerek de veriyi kategorilere ayırabiliriz.

In [49]:
pd.cut(nt,10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (44.0, 51.0], (58.0, 65.0], ..., (51.0, 58.0], (58.0, 65.0], (93.0, 100.0], (93.0, 100.0], (58.0, 65.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

Veriyi çeyrek aralığa ayırmak istersek de qcut methodu kullanırız.

In [50]:
veri=np.random.randn(100)

In [51]:
x=pd.qcut(veri,4)

In [52]:
x

[(-0.692, 0.000549], (-0.692, 0.000549], (0.000549, 0.649], (-2.524, -0.692], (-2.524, -0.692], ..., (0.649, 2.258], (-2.524, -0.692], (0.649, 2.258], (0.649, 2.258], (-0.692, 0.000549]]
Length: 100
Categories (4, interval[float64, right]): [(-2.524, -0.692] < (-0.692, 0.000549] < (0.000549, 0.649] < (0.649, 2.258]]

In [53]:
pd.value_counts(x)

(-2.524, -0.692]      25
(-0.692, 0.000549]    25
(0.000549, 0.649]     25
(0.649, 2.258]        25
dtype: int64

Veri setinde aykırı değerleri görmek isteyebilriz.

In [55]:
veri=pd.DataFrame(np.random.randn(1000,4))

In [56]:
veri.head()

0         1         2         3
0 -0.048197  0.298631  0.163324  1.498796
1  0.826941 -1.117287  0.246237 -0.627631
2  1.102064 -1.896806 -1.729385  1.234149
3  1.442214  1.745744  0.758110 -0.490344
4  0.563164  1.139202  1.281654 -1.288404

In [57]:
veri.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.013356    -0.015219    -0.031513    -0.038924
std       1.000859     0.962830     0.985300     0.964060
min      -3.322433    -3.143392    -3.594358    -3.296947
25%      -0.664486    -0.661850    -0.727259    -0.717463
50%      -0.068540    -0.012006    -0.020001    -0.044486
75%       0.688178     0.652348     0.652286     0.612405
max       3.867948     2.909686     2.744276     2.875695

Birinci indexde mutlak değeri üçten büyük olan değerler ekrana yazdırmak istersek;

In [65]:
sutun=veri[1]

In [66]:
sutun[np.abs(sutun)>3]

618   -3.143392
Name: 1, dtype: float64

Bütün veride mutlak değeri 3 den büyük olan satırları bulmak istersek; any(1)

In [69]:
veri[(np.abs(veri)>3).any(1)]

0         1         2         3
153 -3.003955  0.034880 -1.211172  0.355049
169  0.255880 -0.649772 -3.099737  0.991396
199  3.867948  0.256322  0.097318  0.560562
309 -0.589438  1.141129 -3.087491 -0.742260
544 -1.279342  0.579565 -3.594358  0.352764
618 -0.173168 -3.143392 -0.266547  0.294059
705 -2.046747 -2.119580 -0.419452 -3.296947
803 -3.322433 -0.197681 -1.421903 -0.936083

Değerlerin pozitif mi yoksa negatif mi olduğunu görmek istersek; sign(veri)

In [70]:
np.sign(veri).head()

0    1    2    3
0 -1.0  1.0  1.0  1.0
1  1.0 -1.0  1.0 -1.0
2  1.0 -1.0 -1.0  1.0
3  1.0  1.0  1.0 -1.0
4  1.0  1.0  1.0 -1.0

Series veri yapısını ya da DataFrame veri yapısının satırlarını numpy.random.permutation rastgele sıralama yapabiliriz.

In [71]:
veri=pd.DataFrame(np.arange(12).reshape(4,3))
veri

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [72]:
sira=np.random.permutation(4)
sira

array([0, 2, 3, 1])

In [73]:
veri.take(sira)

0   1   2
0  0   1   2
2  6   7   8
3  9  10  11
1  3   4   5

Rastgele satır değiştirmek istersek sample() methodu kullanılır.

In [75]:
veri.sample()

0   1   2
3  9  10  11

Seçmek istediğimiz satırı geçmek için n=satır sayısı kullanılabilir.

In [76]:
veri.sample(n=2)

0  1  2
1  3  4  5
0  0  1  2

İstatistsel analiz ve Makine Öğrenmesinde kullanılan diğer bir dönüşüm dummy kullanımı:


In [78]:
veri=pd.DataFrame({"harf":["c","b","a","b","b","a"],
                  "sayi":range(6)})

In [79]:
veri

harf  sayi
0    c     0
1    b     1
2    a     2
3    b     3
4    b     4
5    a     5

Her bir sütunda değeri olan ifadeye 1 olmayan ifadeye 0 atamak istersek ge_dummies()

In [80]:
pd.get_dummies(veri["harf"])

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [81]:
veri=np.random.randn(10)
veri

array([ 2.64529381, -0.16794922, -1.06640161,  1.92081507,  1.06884309,
        0.40514165,  1.16269934, -0.62569109, -0.74376852, -0.82508704])

Veri seti dörde ayrıldı, ve her bir değerin bulunduğu aralık 1 ile gösterilmiş oldu.

In [83]:
pd.get_dummies(pd.cut(veri,4))

(-1.07, -0.138]  (-0.138, 0.789]  (0.789, 1.717]  (1.717, 2.645]
0                0                0               0               1
1                1                0               0               0
2                1                0               0               0
3                0                0               0               1
4                0                0               1               0
5                0                1               0               0
6                0                0               1               0
7                1                0               0               0
8                1                0               0               0
9                1                0               0               0